apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-windows-config
  namespace: kube-system
data:
  # Valid values for Calico networking are: "vxlan", "windows-bgp"
  # For non-Calico networking, the only value is "none".
  CALICO_NETWORKING_BACKEND: "vxlan"
  # The Kubernetes API server host and port. This is required to
  # bootstrap Calico for Windows.
  KUBERNETES_SERVICE_HOST: "10.0.4.75"
  KUBERNETES_SERVICE_PORT: "6443"
  # The Kubernetes service clusterIP range configured in your cluster.
  # This must match the service-cluster-ip-range used by kube-apiserver.
  K8S_SERVICE_CIDR: "10.96.0.0/12"
  # The DNS nameservers that will be used in the CNI configuration.
  DNS_NAME_SERVERS: "10.96.0.10"
  # The CNI bin dir. This must match the containerd configuration on the Windows nodes.
  CNI_BIN_DIR: "c:\\opt\\cni\\bin"
  # The CNI conf dir. This must match the containerd configuration on the Windows nodes.
  CNI_CONF_DIR: "c:\\etc\\cni\\net.d"
  # Felix health must be enabled.
  FELIX_HEALTHENABLED: "true"

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-node-windows
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: calico-node-windows
  template:
    metadata:
      labels:
        k8s-app: calico-node-windows
    spec:
      containers:
      - args:
        - .\node\node-service.ps1
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: calico-windows-config
        image: calico/windows:v3.26.1
        imagePullPolicy: Always
        name: node
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        workingDir: c:\\CalicoWindows
      - args:
        - .\felix\felix-service.ps1
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: calico-windows-config
        image: calico/windows:v3.26.1
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - c:\\CalicoWindows\\calico-node.exe
            - -felix-live
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: felix
        readinessProbe:
          exec:
            command:
            - c:\\CalicoWindows\\calico-node.exe
            - -felix-ready
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        workingDir: c:\\CalicoWindows
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - args:
        - .\host-process-install.ps1
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: calico-windows-config
        image: calico/windows:v3.26.1
        imagePullPolicy: Always
        name: install
      nodeSelector:
        kubernetes.io/os: windows
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: NT AUTHORITY\system
      serviceAccount: calico-node
      serviceAccountName: calico-node
